### ISSUE TITLE
Submit paper to JOSS

### ISSUE THREAD

**Issue by barischrooneyj** [barischrooneyj/bridge-sim#167]
Attached is a draft paper, the source code is `paper.md` in the root directory of this repository.

I have labeled a number of issues as `joss` that I either need to or want to complete before submitting the paper.

I am particularly interested in running a non-linear simulation as discussed in #166 , those involved in the OpenSees side of that could then add their name if they wished.

[v1fzhx7qu4gkd6uuktpg.pdf](https://github.com/barischrooneyj/bridge-sim/files/4651059/v1fzhx7qu4gkd6uuktpg.pdf)

**Comment by rozsasarpi** [comment]
Nice first draft! A few suggestions:

- add one image that shows the accuracy of the model prediction against measurements, this can give confidence to the reader that it is good at least in same cases
- describe what are the current capabilities: loads, response collection, parametrization. A table or a list would be more than enough. Unless you plan to have a separate documentation for these.

**Comment by barischrooneyj** [comment]
> Unless you plan to have a separate documentation for these.

"software documentation such as API (Application Programming Interface) functionality should not be in the paper and instead should be outlined in the software documentation."

So I will generate/write proper documentation.

Things to do:

- I will regenerate the influence line plots with bigger scatter plots, removing duplicate X axes and add a title at the very top to avoid duplicate information in the titles. And fix the size issue.
- address some of the issues in this repository to make the software more compliant with JOSS [standards](https://joss.readthedocs.io/en/latest/review_checklist.html).

Draft 2: [btjgjx59gqgrm2g71wod.pdf](https://github.com/barischrooneyj/bridge-sim/files/4652990/btjgjx59gqgrm2g71wod.pdf)

**Comment by rozsasarpi** [comment]
I meant a description on a higher level than an API, even without any relation to programming.
From an engineering/user point of view I would like to know what kind of traffic load, temperature, etc. models are possible. These are the first filters to decide if the tool is applicable to my problem. Even if the package is extendable, I usually look for what is already there. It is up to you to decide how you present things, just keep in mind your target audience.
