### ISSUE TITLE
Smaller Docker image

### ISSUE THREAD

**Issue by barischrooneyj** [barischrooneyj/bridge-sim#170]
The Docker image we build is based on `ubuntu:18.04` but it could be built on something a bit more lightweight.

**Comment by rozsasarpi** [comment]
I have good experience starting with `python:3.7-slim` and adding additional software to it, I use it in CI/CD, unit testing and building documentation. Not sure if it would be enough for your case but maybe.

**Comment by barischrooneyj** [comment]
I think the biggest problem will be installing OpenSees, anything other than that should be alright.

**Comment by barischrooneyj** [comment]
I will mark this as low priority because the time to download the current docker image relative to the run time of simulations should be negligible in most cases.

**Comment by barischrooneyj** [comment]
Most of the filesize comes from dependencies related to OpenSees, not the base image size. Furthermore, moving to a smaller base image e.g. `alpine` increases the build time of the resulting Docker image. Dockerfile has been improved and the image is now 530 MB down from 700.
