### ISSUE TITLE
Automatically publish Docker image

### ISSUE THREAD

**Issue by barischrooneyj** [barischrooneyj/bridge-sim#175]
When a new release is tagged on GitHub

https://github.com/marketplace/actions/build-and-push-docker-images

https://circleci.com/docs/2.0/building-docker-images/

**Comment by barischrooneyj** [comment]
https://circleci.com/docs/2.0/building-docker-images/

**Comment by barischrooneyj** [comment]
After bumping version numbers the soon-to-be built Docker image depends on the soon-to-be published Python package. However building OpenSees takes a while, likely enough time for the Python package to be published.

A potential downside is that OpenSees takes a while, but 3,000 free GitHub Actions minutes is a lot, so it's not really an issue.

A second potential downside is that the Dockerfile is not tested before being published, should be part of #190

**Comment by barischrooneyj** [comment]
> the soon-to-be built Docker image depends on the soon-to-be published Python package

the GitHub actions syntax allows for specifying dependencies, so the Docker image is built and published after the PyPI one

**Comment by jerbaroo** [comment]
Incase new Docker rate limiting for anonymous users becomes an issue:
- https://docs.docker.com/docker-hub/download-rate-limit
- https://circleci.com/docs/2.0/private-images
